# Dependencies
markdown: kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

plugins: [jekyll-paginate]

# Setup
title:            Ethan Cheong
tagline:
description:
url:              http://ethan-cheong.github.io
baseurl:          http://ethan-cheong.github.io

author:
  name:
  url:

paginate:         5

# Custom vars
linkedin:         https://www.linkedin.com/in/ethan-cheong/
github:
  repo:           https://github.com/ethan-cheong
